# Copyright (c) 2024 LazyEdward
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: E2E Browser Test on dev
on: 
  push:
    branches:
      - dev

jobs:
  browser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: E2E on Chrome
        uses: cypress-io/github-action@v6
        with:
          start: 'npm run dev'
          wait-on: 'http://localhost:3000'
          browser: chrome
      - name: E2E on Edge
        uses: cypress-io/github-action@v6
        with:
          start: 'npm run dev'
          wait-on: 'http://localhost:3000'
          browser: edge