# Copyright (c) 2024 LazyEdward
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: E2E Browser Test on main
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on: 
  push:
    branches:
      - main

jobs:
  browser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: E2E on Chrome
        uses: cypress-io/github-action@v6
        with:
          start: 'npm run dev -- -p 3001'
          wait-on: 'http://localhost:3001'
          config: baseUrl=http://localhost:3001
          browser: chrome
      - name: E2E on Edge
        uses: cypress-io/github-action@v6
        with:
          start: 'npm run dev -- -p 3000'
          wait-on: 'http://localhost:3000'
          config: baseUrl=http://localhost:3000
          browser: edge
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}